//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schooldatabase.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySchooldbEntities : DbContext
    {
        public MySchooldbEntities()
            : base("name=MySchooldbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClassDetail> ClassDetails { get; set; }
        public DbSet<StudentDetail> StudentDetails { get; set; }
        public DbSet<StudentMark> StudentMarks { get; set; }
    }
}
